/**
 * Persistence/Data — Core types.
 *
 * Data model for progressions, settings, and URL sharing.
 * All types are plain serializable objects (no classes, no branded strings).
 * Chord symbols are stored verbatim — PD does NOT parse or validate them.
 */

// ---------------------------------------------------------------------------
// Schema versioning
// ---------------------------------------------------------------------------

/** Current schema version for all stored records. */
export const CURRENT_SCHEMA_VERSION = 1;

// ---------------------------------------------------------------------------
// Grid
// ---------------------------------------------------------------------------

/**
 * Supported grid values for progression timing.
 * Duration is implicit via repeated chord tokens (PD-D2).
 * Integration module converts grid → AE beat durations.
 */
export type GridValue = "1/4" | "1/8" | "1/3" | "1/6";

/** Default grid value for new progressions. */
export const DEFAULT_GRID: GridValue = "1/4";

// ---------------------------------------------------------------------------
// Progression
// ---------------------------------------------------------------------------

/**
 * A stored chord progression.
 *
 * - `chords` are verbatim chord symbol strings (e.g., "Dm7", "G7", "Cmaj7").
 *   PD does not validate chord grammar — that is Harmony Core's responsibility.
 * - Duration is implicit: repeated tokens indicate longer durations at the
 *   given `grid` resolution.
 * - `id` is a v4-style UUID string, generated by `generateId()`.
 */
export interface ProgressionRecord {
  readonly id: string;
  readonly schema_version: number;
  readonly title: string;
  readonly tempo_bpm: number;
  readonly grid: GridValue;
  readonly chords: readonly string[];
  readonly notes: string;
  readonly created_at: string;
  readonly updated_at: string;
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

/**
 * User preferences persisted across sessions.
 * Extensible — future fields (view state, theme, etc.) are added here.
 */
export interface SettingsRecord {
  readonly tempo_bpm: number;
}

/** Default settings returned when nothing is stored. */
export const DEFAULT_SETTINGS: Readonly<SettingsRecord> = {
  tempo_bpm: 120,
};

// ---------------------------------------------------------------------------
// URL sharing
// ---------------------------------------------------------------------------

/**
 * Minimal payload for URL-based progression sharing.
 * Subset of ProgressionRecord — excludes id, title, notes, timestamps.
 * Serialized as a human-readable URL fragment (PD-DEV-D5):
 *   `Dm7-G7-Cmaj7&t=120&g=4&v=1`
 */
export interface SharePayload {
  readonly schema_version: number;
  readonly grid: GridValue;
  readonly tempo_bpm: number;
  readonly chords: readonly string[];
}

// ---------------------------------------------------------------------------
// UUID generation
// ---------------------------------------------------------------------------

/**
 * Generate a random UUID (v4-style).
 * Uses `crypto.randomUUID()` when available, falls back to manual generation.
 */
export function generateId(): string {
  if (
    typeof globalThis.crypto !== "undefined" &&
    typeof globalThis.crypto.randomUUID === "function"
  ) {
    return globalThis.crypto.randomUUID();
  }
  // Fallback: manual v4-style UUID
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}
